#!/usr/bin/env python3
"""Add a COLMAP CMake fallback for system OpenImageIO packages.

Ubuntu 20.04 provides libopenimageio-dev without an OpenImageIOConfig.cmake.
COLMAP uses find_package(OpenImageIO), so we add a local FindOpenImageIO.cmake
inside the vendored COLMAP checkout at build time.
"""

from __future__ import annotations

import os
from pathlib import Path


MODULE = r'''# Generated by GLUEMAP's pixi task.
# Fallback finder for distro OpenImageIO packages without OpenImageIOConfig.cmake.

find_package(PkgConfig QUIET)
if(PkgConfig_FOUND)
  pkg_check_modules(PC_OpenImageIO QUIET OpenImageIO)
endif()

find_path(OpenImageIO_INCLUDE_DIR
  NAMES OpenImageIO/imageio.h
  HINTS ${PC_OpenImageIO_INCLUDE_DIRS} ${PC_OpenImageIO_INCLUDEDIR}
)

find_library(OpenImageIO_LIBRARY
  NAMES OpenImageIO
  HINTS ${PC_OpenImageIO_LIBRARY_DIRS} ${PC_OpenImageIO_LIBDIR}
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(OpenImageIO
  REQUIRED_VARS OpenImageIO_LIBRARY OpenImageIO_INCLUDE_DIR
)

if(OpenImageIO_FOUND AND NOT TARGET OpenImageIO::OpenImageIO)
  add_library(OpenImageIO::OpenImageIO UNKNOWN IMPORTED)
  set_target_properties(OpenImageIO::OpenImageIO PROPERTIES
    IMPORTED_LOCATION "${OpenImageIO_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${OpenImageIO_INCLUDE_DIR}"
    INTERFACE_COMPILE_OPTIONS "$<$<COMPILE_LANGUAGE:CXX>:-idirafter>;$<$<COMPILE_LANGUAGE:CXX>:${OpenImageIO_INCLUDE_DIR}>"
  )
endif()
'''

PATCHES = {
    Path("thirdparty/colmap/src/colmap/util/oiio_utils.cc"): {
        "#if OIIO_VERSION >= OIIO_MAKE_VERSION(2, 5, 3)": "#if OIIO_VERSION >= 20503",
    },
    Path("thirdparty/colmap/src/colmap/sensor/bitmap.cc"): {
        "#if OIIO_VERSION >= OIIO_MAKE_VERSION(3, 0, 0)": "#if OIIO_VERSION >= 30000",
    },
}


def main() -> None:
    module_paths = [Path("thirdparty/colmap/cmake/FindOpenImageIO.cmake")]
    if conda_prefix := os.environ.get("CONDA_PREFIX"):
        module_paths.append(Path(conda_prefix) / "share/colmap/cmake/FindOpenImageIO.cmake")

    for path in module_paths:
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and path.read_text() == MODULE:
            print(f"[skip] {path} already installed")
        else:
            path.write_text(MODULE)
            print(f"[patch] wrote {path}")

    for source_path, replacements in PATCHES.items():
        text = source_path.read_text()
        updated = text
        for old, new in replacements.items():
            updated = updated.replace(old, new)
        if updated == text:
            print(f"[skip] {source_path} OIIO version guards already patched")
            continue
        source_path.write_text(updated)
        print(f"[patch] updated {source_path} OIIO version guards")


if __name__ == "__main__":
    main()
